In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
from pandas import ExcelWriter
from pandas import ExcelFile
import numpy as np
from scipy.stats import sem
import os

In [3]:
#Bring in County Population Data
county_pop_df = pd.read_excel('Data\population_by_jurisdiction_and_by_county_-_1970_to_2018_-_09-07-2018.xlsx', sheet_name='Population by County')
county_pop_df

         County  Year  Population
0       Alameda  1970     1071446
1        Alpine  1970         484
2        Amador  1970       11821
3         Butte  1970      101969
4     Calaveras  1970       13585
...         ...   ...         ...
2837     Tulare  2018      475834
2838   Tuolumne  2018       54740
2839    Ventura  2018      859073
2840       Yolo  2018      221270
2841       Yuba  2018       74727

[2842 rows x 3 columns]

In [13]:
#Bring in CoC Data
coc_df=pd.read_csv('Data\coc_county_xref.csv', header=None)
coc_df

         0                1
0   CA-500      Santa Clara
1   CA-501    San Francisco
2   CA-502          Alameda
3   CA-503       Sacramento
4   CA-504           Sonoma
5   CA-505     Contra Costa
6   CA-506         Monterey
7   CA-506       San Benito
8   CA-507            Marin
9   CA-508       Santa Cruz
10  CA-509        Mendocino
11  CA-510       Stanislaus
12  CA-511      San Joaquin
13  CA-512        San Mateo
14  CA-513            Kings
15  CA-513           Tulare
16  CA-514           Madera
17  CA-515           Placer
18  CA-516           Shasta
19  CA-516         Siskiyou
20  CA-516           Lassen
21  CA-516           Plumas
22  CA-516        Del Norte
23  CA-516            Modoc
24  CA-516           Sierra
25  CA-517             Napa
26  CA-518           Solano
27  CA-519            Butte
28  CA-520           Merced
29  CA-521             Yolo
30  CA-522         Humboldt
31  CA-523           Colusa
32  CA-523            Glenn
33  CA-523          Trinity
34  CA-524           Sutter
35  CA-525        El Dorado
36  CA-526           Amador
37  CA-526        Calaveras
38  CA-526         Mariposa
39  CA-526         Tuolumne
40  CA-527           Tehama
41  CA-529             Lake
42  CA-530           Alpine
43  CA-530             Inyo
44  CA-530             Mono
45  CA-600      Los Angeles
46  CA-601        San Diego
47  CA-602           Orange
48  CA-603    Santa Barbara
49  CA-604             Kern
50  CA-606       Long Beach
51  CA-607         Pasadena
52  CA-608        Riverside
53  CA-609   San Bernardino
54  CA-611          Ventura
55  CA-612         Glendale
56  CA-613         Imperial
57  CA-614  San Luis Obispo

In [16]:
# Rename County and CoC Number Column Headers
coc_df.rename(columns = {0:'COC Number'}, inplace = True) 
coc_df.rename(columns = {1:'County'}, inplace = True) 
coc_df

   COC Number           County
0      CA-500      Santa Clara
1      CA-501    San Francisco
2      CA-502          Alameda
3      CA-503       Sacramento
4      CA-504           Sonoma
5      CA-505     Contra Costa
6      CA-506         Monterey
7      CA-506       San Benito
8      CA-507            Marin
9      CA-508       Santa Cruz
10     CA-509        Mendocino
11     CA-510       Stanislaus
12     CA-511      San Joaquin
13     CA-512        San Mateo
14     CA-513            Kings
15     CA-513           Tulare
16     CA-514           Madera
17     CA-515           Placer
18     CA-516           Shasta
19     CA-516         Siskiyou
20     CA-516           Lassen
21     CA-516           Plumas
22     CA-516        Del Norte
23     CA-516            Modoc
24     CA-516           Sierra
25     CA-517             Napa
26     CA-518           Solano
27     CA-519            Butte
28     CA-520           Merced
29     CA-521             Yolo
30     CA-522         Humboldt
31     CA-523           Colusa
32     CA-523            Glenn
33     CA-523          Trinity
34     CA-524           Sutter
35     CA-525        El Dorado
36     CA-526           Amador
37     CA-526        Calaveras
38     CA-526         Mariposa
39     CA-526         Tuolumne
40     CA-527           Tehama
41     CA-529             Lake
42     CA-530           Alpine
43     CA-530             Inyo
44     CA-530             Mono
45     CA-600      Los Angeles
46     CA-601        San Diego
47     CA-602           Orange
48     CA-603    Santa Barbara
49     CA-604             Kern
50     CA-606       Long Beach
51     CA-607         Pasadena
52     CA-608        Riverside
53     CA-609   San Bernardino
54     CA-611          Ventura
55     CA-612         Glendale
56     CA-613         Imperial
57     CA-614  San Luis Obispo

In [4]:
# Only show records for 2018
is_2018 =  county_pop_df['Year']==2018
print(is_2018.head())
pop_2018 = county_pop_df[is_2018]
print(pop_2018)

0    False
1    False
2    False
3    False
4    False
Name: Year, dtype: bool
               County  Year  Population
2784          Alameda  2018     1660202
2785           Alpine  2018        1154
2786           Amador  2018       38094
2787            Butte  2018      227621
2788        Calaveras  2018       45157
2789           Colusa  2018       22098
2790     Contra Costa  2018     1149363
2791        Del Norte  2018       27221
2792        El Dorado  2018      188399
2793           Fresno  2018     1007229
2794            Glenn  2018       28796
2795         Humboldt  2018      136002
2796         Imperial  2018      190624
2797             Inyo  2018       18577
2798             Kern  2018      905801
2799            Kings  2018      151662
2800             Lake  2018       65081
2801           Lassen  2018       30911
2802      Los Angeles  2018    10283729
2803           Madera  2018      158894
2804            Marin  2018      263886
2805         Mariposa  2018       18129
2806        Mendocino  2018       89299
2807           Merced  2018      279977
2808            Modoc  2018        9612
2809             Mono  2018       13822
2810         Monterey  2018      443281
2811             Napa  2018      141294
2812           Nevada  2018       99155
2813           Orange  2018     3284468
2814           Placer  2018      389532
2815           Plumas  2018       19773
2816        Riverside  2018     2415955
2817       Sacramento  2018     1529501
2818       San Benito  2018       57088
2819   San Bernardino  2018     2174938
2820        San Diego  2018     3337456
2821    San Francisco  2018      883963
2822      San Joaquin  2018      758744
2823  San Luis Obispo  2018      280101
2824        San Mateo  2018      774155
2825    Santa Barbara  2018      453457
2826      Santa Clara  2018     1956598
2827       Santa Cruz  2018      276864
2828           Shasta  2018      178271
2829           Sierra  2018        3207
2830         Siskiyou  2018       44612
2831           Solano  2018      439793
2832           Sonoma  2018      503332
2833       Stanislaus  2018      555624
2834           Sutter  2018       97238
2835           Tehama  2018       64039
2836          Trinity  2018       13635
2837           Tulare  2018      475834
2838         Tuolumne  2018       54740
2839          Ventura  2018      859073
2840             Yolo  2018      221270
2841             Yuba  2018       74727

In [25]:
pop_2018.count()

County        58
Year          58
Population    58
dtype: int64

In [28]:
COC_Pop_2018=pd.merge(coc_df, pop_2018, how='left', left_on='County')

TypeError: object of type 'NoneType' has no len()